# topmark:header:start
#
#   project      : TopMark
#   file         : prepare_zensical_docs.py
#   file_relpath : tools/docs/prepare_zensical_docs.py
#   license      : MIT
#   copyright    : (c) 2025 Olivier Biot
#
# topmark:header:end

"""Prepare production Zensical documentation inputs in a disposable staging tree.

Zensical is the production builder. This module bridges only TopMark-owned uses of unsupported
MkDocs plugins in an ignored ``.zensical/`` staging tree:

* ``mkdocs-gen-files`` becomes materialized CLI/configuration pages through
  ``FilesystemDocsWriter``;
* version-token replacement happens before the Zensical build, while GitHub-style callouts use
  Zensical's native ``callouts`` module;
* ``mkdocs-include-markdown-plugin`` becomes a strict local-snippet expander with link rewriting;
* MkDocs ``draft_docs`` and the private ``_snippets/`` files are excluded from publishable inputs.

The include implementation is intentionally *not* a general replacement for the upstream plugin:
it accepts only TopMark's current local Markdown-file directive form and fails for anything else.
Remove these bridges when Zensical provides compatible native support and the pilot no longer needs
them. This command never modifies ``docs/`` or the production configuration.
"""

from __future__ import annotations

import os
import re
import shutil
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as get_version
from pathlib import Path
from typing import TYPE_CHECKING
from typing import Final
from urllib.parse import urlsplit
from urllib.parse import urlunsplit

import tomlkit

from tools.docs.gen_cli_reference_pages import FilesystemDocsWriter
from tools.docs.gen_cli_reference_pages import main as generate_api_pages

if TYPE_CHECKING:
    from urllib.parse import SplitResult

REPOSITORY_ROOT: Final[Path] = Path(__file__).resolve().parents[2]
SOURCE_DOCS_DIR: Final[Path] = REPOSITORY_ROOT / "docs"
SOURCE_CONFIG: Final[Path] = REPOSITORY_ROOT / "zensical.toml"
STAGING_ROOT: Final[Path] = REPOSITORY_ROOT / ".zensical"
STAGING_DOCS_DIR: Final[Path] = STAGING_ROOT / "docs"
STAGING_CONFIG: Final[Path] = STAGING_ROOT / "zensical.toml"
VERSION_TOKEN: Final[str] = "%%TOPMARK_VERSION%%"  # noqa: S105 - documentation macro, not a secret
SNIPPETS_DIRNAME: Final[str] = "_snippets"
INCLUDE_MARKDOWN_RE: Final[re.Pattern[str]] = re.compile(
    r"""^\{%\s*include-markdown\s+(?P<quote>["'])(?P<path>[^"']+)\1\s*%\}$"""
)
INCLUDE_MARKDOWN_PREFIX: Final[str] = "{% include-markdown"
MARKDOWN_LINK_RE: Final[re.Pattern[str]] = re.compile(
    r"(?P<prefix>!?\[[^\]\n]*\]\()(?P<destination><[^>\n]+>|[^()\s]+)(?P<suffix>\))"
)


def _ignore_docs_copy(
    directory: str,
    names: list[str],
) -> set[str]:
    """Exclude non-publishable draft and cache directories from the staging copy.

    Args:
        directory: Directory currently being copied; unused because exclusions are name-based.
        names: Entries in the current source directory.

    Returns:
        Directory names that ``copytree`` must skip.
    """
    del directory
    return {name for name in names if name in {"_drafts", "__pycache__"}}


def _write_staging_config() -> None:
    """Derive a Zensical config whose relative paths are rooted in ``.zensical``.

    The production configuration uses Zensical-native modules. The explicit preparation step
    supplies TopMark-owned generated pages and Markdown transformations. ``mkdocstrings`` needs a
    path back to the repository's source tree.

    Raises:
        RuntimeError: If the expected mkdocstrings source-path setting is no longer present.
    """
    config: tomlkit.TOMLDocument = tomlkit.parse(SOURCE_CONFIG.read_text(encoding="utf-8"))
    try:
        project = config["project"]
        api_autonav = project["plugins"]["api-autonav"]
        mkdocstrings_python = project["plugins"]["mkdocstrings"]["handlers"]["python"]
    except (KeyError, TypeError) as error:
        raise RuntimeError("Could not locate API source paths in zensical.toml") from error

    if api_autonav["modules"] != ["src/topmark"] or mkdocstrings_python["paths"] != ["src"]:
        raise RuntimeError("Could not locate API source paths in zensical.toml")

    project["docs_dir"] = "docs"
    project["site_dir"] = "site"
    api_autonav["modules"] = ["../src/topmark"]
    mkdocstrings_python["paths"] = ["../src"]
    staging_text: str = tomlkit.dumps(config)
    staging_text += "\n# Generated by tools/docs/prepare_zensical_docs.py; do not edit.\n"
    STAGING_CONFIG.write_text(staging_text, encoding="utf-8")


def _installed_topmark_version() -> str:
    """Return the installed TopMark version used by the documentation build.

    Returns:
        Installed TopMark distribution version, or ``"dev"`` when unavailable.
    """
    try:
        return get_version("topmark")
    except PackageNotFoundError:
        return "dev"


def _substitute_version_tokens(
    docs_dir: Path,
    version: str,
) -> None:
    """Replace TopMark version tokens in every staged Markdown file.

    Args:
        docs_dir: Root of the disposable staged documentation tree.
        version: Version string to substitute for ``%%TOPMARK_VERSION%%``.
    """
    for markdown_path in sorted(docs_dir.rglob("*.md")):
        content: str = markdown_path.read_text(encoding="utf-8")
        if VERSION_TOKEN in content:
            markdown_path.write_text(content.replace(VERSION_TOKEN, version), encoding="utf-8")


def _included_markdown_path(
    docs_dir: Path,
    directive_path: str,
) -> Path:
    """Resolve one TopMark include directive to a Markdown file in the staging tree.

    Args:
        docs_dir: Root of the disposable staged documentation tree.
        directive_path: Unquoted path from an ``include-markdown`` directive.

    Returns:
        Resolved path to the staged included Markdown file.

    Raises:
        ValueError: If the path is not a local Markdown file within ``docs_dir``.
        FileNotFoundError: If the requested staged snippet does not exist.
    """
    unescaped_path: str = directive_path.removeprefix("\\")
    relative_path: Path = Path(unescaped_path)
    if relative_path.is_absolute() or relative_path.suffix != ".md":
        raise ValueError(f"Include path must be a relative Markdown file: {directive_path!r}")

    docs_root: Path = docs_dir.resolve()
    included_path: Path = (docs_root / relative_path).resolve()
    try:
        included_path.relative_to(docs_root)
    except ValueError as error:
        message: str = f"Include path escapes the staged docs tree: {directive_path!r}"
        raise ValueError(message) from error

    if not included_path.is_file():
        raise FileNotFoundError(f"Included Markdown file does not exist: {directive_path!r}")
    return included_path


def _rewrite_relative_urls(
    markdown: str,
    source_path: Path,
    target_path: Path,
    docs_dir: Path,
) -> str:
    """Rewrite local Markdown-link destinations for their final inclusion page.

    Args:
        markdown: Included Markdown content.
        source_path: Path of the source snippet that owns the original links.
        target_path: Page into which the content is ultimately inserted.
        docs_dir: Root of the disposable staged documentation tree.

    Returns:
        Included content with local relative link destinations rewritten.
    """
    docs_root: Path = docs_dir.resolve()

    def _replace(match: re.Match[str]) -> str:
        destination: str = match.group("destination")
        wrapped: bool = destination.startswith("<") and destination.endswith(">")
        raw_destination: str = destination[1:-1] if wrapped else destination
        parsed: SplitResult = urlsplit(raw_destination)
        is_nonlocal: bool = bool(parsed.scheme or parsed.netloc) or raw_destination.startswith(
            ("/", "#")
        )
        if not parsed.path or is_nonlocal:
            return match.group(0)

        linked_path: Path = (source_path.parent / parsed.path).resolve()
        try:
            linked_path.relative_to(docs_root)
        except ValueError:
            return match.group(0)

        rewritten_path: str = os.path.relpath(linked_path, target_path.parent).replace(os.sep, "/")
        rewritten_destination: str = urlunsplit(
            (parsed.scheme, parsed.netloc, rewritten_path, parsed.query, parsed.fragment)
        )
        if wrapped:
            rewritten_destination = f"<{rewritten_destination}>"
        return f"{match.group('prefix')}{rewritten_destination}{match.group('suffix')}"

    return MARKDOWN_LINK_RE.sub(_replace, markdown)


def _expand_markdown_file(
    markdown_path: Path,
    target_path: Path,
    docs_dir: Path,
    include_stack: tuple[Path, ...],
    *,
    rewrite_urls: bool,
) -> str:
    """Expand supported include directives in one staged Markdown file.

    Directives are deliberately restricted to TopMark's current one-line local-file form. They are
    ignored inside fenced code blocks, so documentation about the directive itself remains literal.

    Args:
        markdown_path: Staged Markdown file currently being expanded.
        target_path: Final page into which this file's content is inserted.
        docs_dir: Root of the disposable staged documentation tree.
        include_stack: Included files currently being traversed for cycle detection.
        rewrite_urls: Whether links owned by this file must be rewritten for ``target_path``.

    Returns:
        Markdown content with supported include directives expanded.

    Raises:
        ValueError: If a directive uses unsupported syntax or includes form a cycle.
    """
    content: str = markdown_path.read_text(encoding="utf-8")
    result: list[str] = []
    fence_marker: str | None = None

    for line in content.splitlines(keepends=True):
        stripped_line: str = line.strip()
        if stripped_line.startswith(("```", "~~~")):
            marker: str = stripped_line[:3]
            if fence_marker is None:
                fence_marker = marker
            elif marker == fence_marker:
                fence_marker = None
            result.append(line)
            continue

        if fence_marker is not None:
            result.append(line)
            continue

        match: re.Match[str] | None = INCLUDE_MARKDOWN_RE.fullmatch(stripped_line)
        if match is None:
            if stripped_line.startswith(INCLUDE_MARKDOWN_PREFIX):
                raise ValueError(
                    f"Unsupported include-markdown directive in {markdown_path}: {stripped_line}"
                )
            if rewrite_urls:
                line = _rewrite_relative_urls(line, markdown_path, target_path, docs_dir)
            result.append(line)
            continue

        included_path: Path = _included_markdown_path(docs_dir, match.group("path"))
        if included_path in include_stack:
            cycle: str = " -> ".join(
                path.relative_to(docs_dir).as_posix() for path in include_stack
            )
            included_name: str = included_path.relative_to(docs_dir).as_posix()
            raise ValueError(f"Include cycle detected: {cycle} -> {included_name}")

        included_content: str = _expand_markdown_file(
            included_path,
            target_path,
            docs_dir,
            (*include_stack, included_path),
            rewrite_urls=True,
        )
        result.append(included_content)

    return "".join(result)


def _expand_include_markdown_directives(docs_dir: Path) -> None:
    """Expand TopMark's local include directives and remove the now-private snippet files.

    Args:
        docs_dir: Root of the disposable staged documentation tree.
    """
    snippets_dir: Path = docs_dir / SNIPPETS_DIRNAME
    markdown_paths: list[Path] = sorted(
        path for path in docs_dir.rglob("*.md") if not path.is_relative_to(snippets_dir)
    )
    for markdown_path in markdown_paths:
        markdown_path.write_text(
            _expand_markdown_file(
                markdown_path,
                markdown_path,
                docs_dir,
                (markdown_path,),
                rewrite_urls=False,
            ),
            encoding="utf-8",
        )

    if snippets_dir.exists():
        shutil.rmtree(snippets_dir)


def prepare() -> None:
    """Recreate the complete production Zensical documentation input tree.

    Raises:
        RuntimeError: If required project documentation inputs are missing.
    """
    if not SOURCE_DOCS_DIR.is_dir() or not SOURCE_CONFIG.is_file():
        raise RuntimeError("Run the Zensical preparation command from a complete TopMark checkout")

    if STAGING_ROOT.exists():
        shutil.rmtree(STAGING_ROOT)

    shutil.copytree(SOURCE_DOCS_DIR, STAGING_DOCS_DIR, ignore=_ignore_docs_copy)
    _write_staging_config()
    generate_api_pages(FilesystemDocsWriter(STAGING_DOCS_DIR))
    _expand_include_markdown_directives(STAGING_DOCS_DIR)
    _substitute_version_tokens(STAGING_DOCS_DIR, _installed_topmark_version())


def main() -> None:
    """Prepare inputs and print the exact follow-up Zensical build command."""
    prepare()
    print(f"Prepared disposable Zensical docs in {STAGING_DOCS_DIR.relative_to(REPOSITORY_ROOT)}")
    print("Next: .venv/bin/zensical build --config-file .zensical/zensical.toml --strict")


if __name__ == "__main__":
    main()
