# topmark:header:start
#
#   file         : .pre-commit-hooks.yaml
#   file_relpath : .pre-commit-hooks.yaml
#   project      : TopMark
#   license      : MIT
#   copyright    : (c) 2025 Olivier Biot
#
# topmark:header:end

# This file defines the pre-commit hooks for TopMark

- id: topmark-check
  name: topmark-check
  description: "Validate file headers with TopMark; non-compliant or unsupported files are reported, exit non-zero if fixes are needed."
  entry: topmark --quiet --skip-compliant --skip-unsupported  # Only show non-compliant, supported entries
  language: python
  pass_filenames: true
  stages: [pre-commit, pre-push, manual]
  # Let TopMark decide what files are in-scope; pre-commit still passes the changed paths.
  # You can narrow further with "files:" or "types:", if desired.
  additional_dependencies: []  # e.g., ["topmark==0.2.0"] if you want a PyPI install instead of building from source

- id: topmark-apply
  name: topmark-apply
  description:  "Insert or update headers with TopMark; intended for manual runs (may modify files)."
  entry: topmark --quiet --skip-compliant --skip-unsupported --apply
  language: python
  pass_filenames: true
  stages: [manual]
  require_serial: true  # safer for file edits
  additional_dependencies: []