- id: topmark-check
  name: TopMark — check headers (non-destructive)
  description: Validate file headers using TopMark; fails if headers need changes.
  entry: topmark --skip-compliant  # Only show non-compliant entries
  language: python
  pass_filenames: true
  stages: [pre-commit, pre-push, manual]
  # Let TopMark decide what files are in-scope; pre-commit still passes the changed paths.
  # You can narrow further with "files:" or "types:", if desired.
  additional_dependencies: []  # e.g., ["topmark==0.2.0"] if you want a PyPI install instead of building from source

- id: topmark-apply
  name: TopMark — apply headers (destructive; requires --apply)
  description: Apply/insert headers. Intended for manual runs (not automatic on commit).
  entry: topmark --apply
  language: python
  pass_filenames: true
  stages: [manual]
  require_serial: true  # safer for file edits
  additional_dependencies: []