# topmark:header:start
#
#   file         : topmark.toml
#   file_relpath : topmark.toml
#   project      : TopMark
#   license      : MIT
#   copyright    : (c) 2025 Olivier Biot
#
# topmark:header:end


#################################
# Default TopMark configuration #
#################################
# This file is used to define the default configuration for TopMark.


# ==========================
# Header field configuration
# ==========================


[header]
# Configuration for header fields and metadata to include in generated headers

# List of fields to include in the header.
# Available fields include 'file', 'file_relpath', 'author', 'date', 'license', etc.
# You can define your own fields as well.

# TODO: review the fields: builtin field types and custom fields

fields = ["file", "file_relpath", "project", "license", "copyright"]

# ========================
# TopMark field definition
# ========================


[fields]

# Project name to include in the header
project = "TopMark"

# License to include in the header. Example values: 'MIT', 'GPL-3.0', 'Apache-2.0'
license = "MIT"

# Copyright statement to include in the header.
copyright = "(c) 2025 Olivier Biot" # Update according to your needs


# ========================
# Formatting configuration
# ========================

[formatting]
# Formatting options for header rendering.

# Align the fields (colons) in the header for better readability. Values: true or false.
align_fields = true

# Render the file header to the console as raw (true) or formatted (false)
raw_header = true


# ===================
# Files configuration
# ===================

[files]

# Specify (filter) file types:
file_types = "markdown"


# ============================
# END of TopMark Configuration
# ============================
## === END of TopMark Configuration ===
