# topmark:header:start
#
#   project      : TopMark
#   file         : types.py
#   file_relpath : src/topmark/api/types.py
#   license      : MIT
#   copyright    : (c) 2025 Olivier Biot
#
# topmark:header:end

"""Stable public types for the TopMark API.

This module defines enums, dataclasses, and TypedDicts that appear in:
- public function signatures in [`topmark.api`][topmark.api]
- public return values (e.g., `RunResult`)

These shapes follow the project's semver policy. Internal domain objects may be richer and
are allowed to evolve independently (e.g., internal diagnostics or pipeline views).
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TYPE_CHECKING
from typing import Final
from typing import Literal
from typing import TypedDict

from topmark.core.logging import TopmarkLogger
from topmark.core.logging import get_logger

if TYPE_CHECKING:
    from collections.abc import Mapping
    from collections.abc import Sequence
    from pathlib import Path


logger: TopmarkLogger = get_logger(__name__)

DiagnosticLevelLiteral = Literal["info", "warning", "error"]
"""Allowed diagnostic severity levels in the public API."""


class DiagnosticEntry(TypedDict):
    """JSON-friendly diagnostic entry for API consumers.

    Notes:
        - Uses string literal levels for stability and easy serialization.
        - Mirrors internal pipeline diagnostics but does not expose internal enums/classes.
    """

    level: DiagnosticLevelLiteral
    message: str


class DiagnosticTotals(TypedDict):
    """Aggregate diagnostic counts across the returned *view*.

    Attributes:
        info: Number of info diagnostics.
        warning: Number of warning diagnostics.
        error: Number of error diagnostics.
        total: Sum of all diagnostics.
    """

    info: int
    warning: int
    error: int
    total: int


class Outcome(str, Enum):
    """Per-file outcome bucket.

    Values mirror CLI semantics. Consumers should use `Outcome` (and `.value`) for
    programmatic decisions rather than relying on human labels.
    """

    PENDING = "pending"
    ERROR = "error"
    # File skipped (not processed)
    SKIPPED = "skipped"
    # File already complies
    UNCHANGED = "unchanged"
    # A change was detected but not applied
    WOULD_CHANGE = "would change"
    WOULD_INSERT = "would insert"
    WOULD_UPDATE = "would update"
    WOULD_STRIP = "would strip"
    # Changes have been applied
    CHANGED = "changed"
    INSERTED = "inserted"
    UPDATED = "updated"
    STRIPPED = "stripped"


OUTCOME_ORDER: Final[tuple[Outcome, ...]] = (
    Outcome.PENDING,
    Outcome.SKIPPED,
    Outcome.UNCHANGED,
    Outcome.WOULD_CHANGE,
    Outcome.WOULD_INSERT,
    Outcome.WOULD_UPDATE,
    Outcome.WOULD_STRIP,
    Outcome.CHANGED,
    Outcome.INSERTED,
    Outcome.UPDATED,
    Outcome.STRIPPED,
    Outcome.ERROR,
)


@dataclass(frozen=True)
class FileResult:
    """Result for a single file after pipeline execution and view filtering.

    This object is a **pure data carrier** intended for machine consumption
    (JSON, NDJSON, API callers). It deliberately contains no pre-rendered
    human-facing messages or ANSI formatting.

    Attributes:
        path: Absolute or workspace-relative path to the file.
        outcome: Stable, high-level outcome bucket describing the
            file's final state (e.g. ``UNCHANGED``, ``WOULD_UPDATE``, ``ERROR``).
        diff: Unified diff as a string when available.
            ``None`` if diffs were not requested or are not applicable.
        bucket_key: Public bucket identifier corresponding to the
            outcome classification (typically ``outcome.value``). This key is
            stable and suitable for aggregation and machine processing.
        bucket_label: Human-oriented explanation for the bucket,
            derived from the first-seen classification reason. Intended for
            display purposes only.

    Notes:
        - ``outcome`` is the **authoritative semantic signal** and is stable
          across versions.
        - ``bucket_key`` mirrors the public outcome value and exists to support
          uniform bucketing and summaries.
        - ``bucket_label`` is best-effort, may change between versions, and
          should not be relied upon for programmatic decisions.
        - Any human-readable or colorized summaries must be generated by
          presentation helpers (e.g. in ``topmark.presentation``), not by the API.
    """

    path: Path
    outcome: Outcome
    diff: str | None
    bucket_key: str | None = None
    bucket_label: str | None = None


@dataclass(frozen=True)
class RunResult:
    """Aggregate result of a TopMark run after view-level filtering.

    This structure summarizes per-file results, outcome counts, and diagnostics
    in a JSON-friendly form suitable for API consumers and machine-readable
    output formats.

    Attributes:
        files: Ordered sequence of per-file results
            **after view filtering** (e.g. respecting ``skip_compliant`` or
            ``skip_unsupported``).
        summary: Mapping from public outcome values
            (``Outcome.value``) to counts for the returned ``files``.
        had_errors: ``True`` if any file encountered an error during
            processing, computed from the **unfiltered** result set so that
            real errors are not hidden by view filters.
        skipped: Number of results excluded by view filtering.
        written: Number of files successfully written
            (only meaningful when ``apply=True``; otherwise ``0``).
        failed: Number of files that failed to write
            (only meaningful when ``apply=True``; otherwise ``0``).
        bucket_summary: Optional summary aggregated
            by bucket key rather than by outcome alone. When present, this is
            primarily intended to support CLI-style reporting.
        diagnostics: Optional mapping
            from file path to public diagnostic entries for the **returned view**.
        diagnostic_totals: Aggregate diagnostic counts
            across the returned (filtered) view.
        diagnostic_totals_all: Aggregate diagnostic
            counts across the entire run (pre view filtering).

    Notes:
        - ``summary`` is strictly derived from ``files`` and reflects only the
          filtered view.
        - ``bucket_summary`` is optional and more presentation-oriented than
          ``summary``; consumers should not assume it is always present.
        - No fields in this object contain formatted or colorized output.
          Presentation is the responsibility of higher layers (CLI or UI).
    """

    files: Sequence[FileResult]
    summary: Mapping[str, int]
    had_errors: bool
    skipped: int = 0
    written: int = 0
    failed: int = 0
    bucket_summary: Mapping[str, int] | None = None
    diagnostics: dict[str, list[DiagnosticEntry]] | None = None
    diagnostic_totals: DiagnosticTotals | None = None
    diagnostic_totals_all: DiagnosticTotals | None = None


class FileTypePolicyInfo(TypedDict, total=True):
    r"""Stable metadata describing header insertion/stripping policy for a file type.

    This typed dict represents a
    [`topmark.filetypes.policy.FileTypeHeaderPolicy`][topmark.filetypes.policy.FileTypeHeaderPolicy]
    instance.

    Attributes:
        supports_shebang: Whether this file type commonly starts with a POSIX
            shebang (e.g., ``#!/usr/bin/env bash``). When ``True``, processors may
            skip a leading shebang during placement.
        encoding_line_regex: Optional regex (string) that matches an
            encoding declaration line *immediately after* a shebang (e.g., Python
            PEP 263). When provided and a shebang was skipped, a matching line is
            also skipped for placement.
        pre_header_blank_after_block: Number of blank lines to place between a
            preamble block (shebang/encoding or similar) and the header. Typically 1.
        ensure_blank_after_header: Ensure exactly one blank line follows the
            header when body content follows. No extra blank is added at EOF.
        blank_collapse_mode: How to identify and collapse *blank*
            lines around the header during insert/strip repairs. See
            [`BlankCollapseMode`][topmark.filetypes.policy.BlankCollapseMode] for semantics.
        blank_collapse_extra: Additional characters to treat as blank **in
            addition** to those covered by ``blank_collapse_mode``. For example,
            set to ``\"\\x0c\"`` to consider form-feed collapsible for a given type.
    """

    supports_shebang: bool
    encoding_line_regex: str | None

    pre_header_blank_after_block: int
    ensure_blank_after_header: bool

    # How to identify and collapse “blank” lines around the header during insert/strip repairs.
    blank_collapse_mode: str
    blank_collapse_extra: str


class FileTypeInfo(TypedDict, total=True):
    """Stable metadata about a registered file type.

    Attributes:
        local_key: File type local key (compatibility identifier).
        namespace: Namespace that owns the file type.
        qualified_key: Canonical file type key.
        description: Human description.
        bound: Whether the file type currently has an effective processor binding.
        extensions: Known filename extensions (without dots).
        filenames: Exact filenames matched (e.g., ``"Makefile"``).
        patterns: Full-match regular-expression patterns.
        skip_processing: Whether the type is discoverable but not processed.
        has_content_matcher: Whether a content matcher exists.
        has_insert_checker: Whether a header insert checker exists.
        policy: Policy/strategy for header placement.
    """

    local_key: str
    namespace: str
    qualified_key: str

    description: str

    bound: bool

    extensions: Sequence[str]
    filenames: Sequence[str]
    patterns: Sequence[str]
    skip_processing: bool
    has_content_matcher: bool
    has_insert_checker: bool
    policy: FileTypePolicyInfo


class ProcessorInfo(TypedDict, total=True):
    """Stable metadata about a registered header processor.

    Attributes:
        local_key: Processor local key (compatibility identifier).
        namespace: Namespace that owns the processor.
        qualified_key: Canonical processor key.
        description: Human description.
        bound: Whether the processor currently participates in at least one
            effective file-type binding.
        line_indent: Line comment indent (if applicable).
        line_prefix: Line comment prefix (if applicable).
        line_suffix: Line comment suffix (if applicable).
        block_prefix: Block comment prefix (if applicable).
        block_suffix: Block comment suffix (if applicable).
    """

    local_key: str
    namespace: str
    qualified_key: str

    description: str

    bound: bool

    line_indent: str
    line_prefix: str
    line_suffix: str
    block_prefix: str
    block_suffix: str


class BindingInfo(TypedDict, total=True):
    """Stable metadata about an effective file-type-to-processor binding.

    Attributes:
        file_type_key: Canonical file type key.
        file_type_local_key: File type local key.
        file_type_namespace: Namespace that owns the file type.
        processor_key: Canonical processor key.
        processor_local_key: Processor local key.
        processor_namespace: Namespace that owns the processor.
        file_type_description: Human description of the file type.
        processor_description: Human description of the processor.
    """

    file_type_key: str
    file_type_local_key: str
    file_type_namespace: str

    processor_key: str
    processor_local_key: str
    processor_namespace: str

    file_type_description: str
    processor_description: str
