# topmark:header:start
#
#   project      : TopMark
#   file         : types.py
#   file_relpath : src/topmark/api/types.py
#   license      : MIT
#   copyright    : (c) 2025 Olivier Biot
#
# topmark:header:end

"""Stable public types for the TopMark API.

This module defines enums, dataclasses, and TypedDicts that appear in the
public function signatures and return values of [`topmark.api`][topmark.api]. These
shapes follow the project's semver policy.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TYPE_CHECKING, TypedDict

from topmark.config.logging import TopmarkLogger, get_logger

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence
    from pathlib import Path

    from .public_types import PublicDiagnostic

logger: TopmarkLogger = get_logger(__name__)


class DiagnosticTotals(TypedDict):
    """Aggregate diagnostic counts across the returned *view*.

    Attributes:
        info: Number of info diagnostics.
        warning: Number of warning diagnostics.
        error: Number of error diagnostics.
        total: Sum of all diagnostics.
    """

    info: int
    warning: int
    error: int
    total: int


class Outcome(str, Enum):
    """Per-file outcome bucket.

    Values mirror CLI semantics:
      - ``PENDING``: Outcome is undecided.
      - ``UNCHANGED``: No changes needed.
      - ``WOULD_CHANGE``: Dry-run detected changes would be made (apply=False).
      - ``CHANGED``: A write occurred (apply=True).
      - ``SKIPPED``: File processing skipped.
    """

    PENDING = "pending"
    ERROR = "error"
    # File skipped (not processed)
    SKIPPED = "skipped"
    # File already complies
    UNCHANGED = "unchanged"
    # A change was detected but not applied
    WOULD_CHANGE = "would change"
    WOULD_INSERT = "would insert"
    WOULD_UPDATE = "would update"
    WOULD_STRIP = "would strip"
    # Changes have been applied
    CHANGED = "changed"
    INSERTED = "inserted"
    UPDATED = "updated"
    STRIPPED = "stripped"


@dataclass(frozen=True)
class FileResult:
    """Result for a single file after pipeline execution and view filtering.

    This object is a **pure data carrier** intended for machine consumption
    (JSON, NDJSON, API callers). It deliberately contains no pre-rendered
    human-facing messages or ANSI formatting.

    Attributes:
        path: Absolute or workspace-relative path to the file.
        outcome: Stable, high-level outcome bucket describing the
            file's final state (e.g. ``UNCHANGED``, ``WOULD_UPDATE``, ``ERROR``).
        diff: Unified diff as a string when available.
            ``None`` if diffs were not requested or are not applicable.
        bucket_key: Public bucket identifier corresponding to the
            outcome classification (typically ``outcome.value``). This key is
            stable and suitable for aggregation and machine processing.
        bucket_label: Human-oriented explanation for the bucket,
            derived from the first-seen classification reason. Intended for
            display purposes only.

    Notes:
        - ``outcome`` is the **authoritative semantic signal** and is stable
          across versions.
        - ``bucket_key`` mirrors the public outcome value and exists to support
          uniform bucketing and summaries.
        - ``bucket_label`` is best-effort, may change between versions, and
          should not be relied upon for programmatic decisions.
        - Any human-readable or colorized summaries must be generated by
          presentation helpers (e.g. in ``topmark.cli_shared``), not by the API.
    """

    path: Path
    outcome: Outcome
    diff: str | None
    bucket_key: str | None = None
    bucket_label: str | None = None


@dataclass(frozen=True)
class RunResult:
    """Aggregate result of a TopMark run after view-level filtering.

    This structure summarizes per-file results, outcome counts, and diagnostics
    in a JSON-friendly form suitable for API consumers and machine-readable
    output formats.

    Attributes:
        files: Ordered sequence of per-file results
            **after view filtering** (e.g. respecting ``skip_compliant`` or
            ``skip_unsupported``).
        summary: Mapping from public outcome values
            (``Outcome.value``) to counts for the returned ``files``.
        had_errors: ``True`` if any file encountered an error during
            processing, computed from the **unfiltered** result set so that
            real errors are not hidden by view filters.
        skipped: Number of results excluded by view filtering.
        written: Number of files successfully written
            (only meaningful when ``apply=True``; otherwise ``0``).
        failed: Number of files that failed to write
            (only meaningful when ``apply=True``; otherwise ``0``).
        bucket_summary: Optional summary aggregated
            by bucket key rather than by outcome alone. When present, this is
            primarily intended to support CLI-style reporting.
        diagnostics: Optional mapping
            from file path to public diagnostic entries for the **returned view**.
        diagnostic_totals: Aggregate diagnostic counts
            across the returned (filtered) view.
        diagnostic_totals_all: Aggregate diagnostic
            counts across the entire run (pre view filtering).

    Notes:
        - ``summary`` is strictly derived from ``files`` and reflects only the
          filtered view.
        - ``bucket_summary`` is optional and more presentation-oriented than
          ``summary``; consumers should not assume it is always present.
        - No fields in this object contain formatted or colorized output.
          Presentation is the responsibility of higher layers (CLI or UI).
    """

    files: Sequence[FileResult]
    summary: Mapping[str, int]
    had_errors: bool
    skipped: int = 0
    written: int = 0
    failed: int = 0
    bucket_summary: Mapping[str, int] | None = None
    diagnostics: dict[str, list[PublicDiagnostic]] | None = None
    diagnostic_totals: DiagnosticTotals | None = None
    diagnostic_totals_all: DiagnosticTotals | None = None


# Tiny intent object used by check()/strip() to gate writes
@dataclass(frozen=True)
class WritePolicy:
    """Policy controlling which files to write when `apply=True`.

    Attributes:
        allow_insert: Permit inserting a new header (add-only).
        allow_replace: Permit replacing/updating an existing header (update-only).
        allow_remove: Permit removing a header (strip).
    """

    allow_insert: bool = False  # add missing headers
    allow_replace: bool = False  # update existing non-compliant headers
    allow_remove: bool = False  # strip headers


class FileTypeInfo(TypedDict, total=False):
    """Metadata about a registered file type.

    Attributes:
        name: Identifier of the file type (e.g., ``"python"``).
        description: Human description.
        supported: File type is supported by a header processor
        processor_name: Name of the header processor registered to the file type
            or `None`
        extensions: Known filename extensions (without dots).
        filenames: Exact filenames matched (e.g., ``"Makefile"``).
        patterns: Glob-like patterns.
        skip_processing: Whether the type is discoverable but not processed.
        content_matcher: Whether a content matcher is configured.
        header_policy: Policy/strategy name for header placement.
    """

    name: str
    description: str
    supported: bool
    processor_name: str | None
    extensions: Sequence[str]
    filenames: Sequence[str]
    patterns: Sequence[str]
    skip_processing: bool
    content_matcher: bool
    header_policy: str


class ProcessorInfo(TypedDict, total=False):
    """Metadata about a registered header processor.

    Attributes:
        name: Processor identifier (e.g., ``"pound"``, ``"slash"``, ``"xml"``).
        description: Human description.
        line_prefix: Line comment prefix (if applicable).
        line_suffix: Line comment suffix (if applicable).
        block_prefix: Block comment prefix (if applicable).
        block_suffix: Block comment suffix (if applicable).
    """

    name: str
    description: str
    line_prefix: str
    line_suffix: str
    block_prefix: str
    block_suffix: str
