# topmark:header:start
#
#   project      : TopMark
#   file         : test_zensical_docs_preparation.py
#   file_relpath : tests/dev_validation/test_zensical_docs_preparation.py
#   license      : MIT
#   copyright    : (c) 2025 Olivier Biot
#
# topmark:header:end

"""Tests for the disposable Zensical documentation-preparation helpers."""

from __future__ import annotations

import sys
from typing import TYPE_CHECKING

import pytest
import tomlkit

from tools.docs import prepare_zensical_docs
from tools.docs.gen_cli_reference_pages import FilesystemDocsWriter

if TYPE_CHECKING:
    from pathlib import Path


def test_filesystem_docs_writer_writes_relative_page(
    tmp_path: Path,
) -> None:
    """The staging writer materializes nested generated documentation pages."""
    docs_dir: Path = tmp_path / "docs"
    writer = FilesystemDocsWriter(docs_dir)

    with writer.open("api/internals/topmark/api/index.md", "w") as page:
        page.write("# API\n")

    generated_page = docs_dir / "api/internals/topmark/api/index.md"
    assert generated_page.read_text(encoding="utf-8") == "# API\n"


@pytest.mark.parametrize(
    "path",
    [
        "/absolute.md",
        "../outside.md",
        r"..\outside.md",
    ],
)
def test_filesystem_docs_writer_rejects_escaping_paths(
    tmp_path: Path,
    path: str,
) -> None:
    """The staging writer cannot create files outside its documentation root."""
    writer = FilesystemDocsWriter(tmp_path / "docs")

    with pytest.raises(ValueError, match="must be relative"):
        writer.open(path, "w")


@pytest.mark.skipif(sys.platform != "win32", reason="Windows drive semantics only")
@pytest.mark.parametrize(
    "path",
    [
        r"\rooted.md",
        r"C:\absolute.md",
        r"C:drive-relative.md",
    ],
)
def test_filesystem_docs_writer_rejects_windows_rooted_or_drive_paths(
    tmp_path: Path,
    path: str,
) -> None:
    """The staging writer rejects Windows-rooted and drive-qualified paths."""
    writer = FilesystemDocsWriter(tmp_path / "docs")

    with pytest.raises(ValueError, match="must be relative"):
        writer.open(path, "w")


def test_write_staging_config_uses_staged_docs_and_source_tree(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """The derived config redirects docs and mkdocstrings paths for the staging tree."""
    source_config: Path = tmp_path / "zensical.toml"
    staging_config: Path = tmp_path / ".zensical" / "zensical.toml"
    source_config.write_text(
        "[project]\n\n  [project.plugins.api-autonav]\n"
        '  modules                       = ["src/topmark"]\n'
        "\n    [project.plugins.mkdocstrings.handlers.python]\n"
        '    paths = ["src"]\n',
        encoding="utf-8",
    )
    staging_config.parent.mkdir()
    monkeypatch.setattr(
        prepare_zensical_docs,
        "SOURCE_CONFIG",
        source_config,
    )
    monkeypatch.setattr(
        prepare_zensical_docs,
        "STAGING_CONFIG",
        staging_config,
    )

    prepare_zensical_docs._write_staging_config()  # pyright: ignore[reportPrivateUsage]

    staging_text: str = staging_config.read_text(encoding="utf-8")
    staging_config_document = tomlkit.parse(staging_text)
    project = staging_config_document["project"]

    assert project["docs_dir"] == "docs"
    assert project["site_dir"] == "site"
    assert project["plugins"]["api-autonav"]["modules"] == ["../src/topmark"]
    assert project["plugins"]["mkdocstrings"]["handlers"]["python"]["paths"] == ["../src"]
    assert staging_text.endswith(
        "# Generated by tools/docs/prepare_zensical_docs.py; do not edit.\n"
    )


def test_substitute_version_tokens_rewrites_all_staged_markdown(
    tmp_path: Path,
) -> None:
    """Version tokens are expanded in handwritten and generated staged pages."""
    handwritten_page: Path = tmp_path / "index.md"
    generated_page: Path = tmp_path / "api" / "reference.md"
    generated_page.parent.mkdir()
    handwritten_page.write_text("# TopMark %%TOPMARK_VERSION%%\n", encoding="utf-8")
    generated_page.write_text("%%TOPMARK_VERSION%% API\n", encoding="utf-8")

    prepare_zensical_docs._substitute_version_tokens(  # pyright: ignore[reportPrivateUsage]
        tmp_path,
        "1.2.3",
    )

    assert handwritten_page.read_text(encoding="utf-8") == "# TopMark 1.2.3\n"
    assert generated_page.read_text(encoding="utf-8") == "1.2.3 API\n"


def test_expand_include_markdown_directives_expands_nested_snippets_and_rewrites_links(
    tmp_path: Path,
) -> None:
    """Local snippets are expanded recursively with links valid from their final page."""
    docs_dir: Path = tmp_path / "docs"
    page_path: Path = docs_dir / "ci" / "page.md"
    snippets_dir: Path = docs_dir / "_snippets"
    page_path.parent.mkdir(parents=True)
    snippets_dir.mkdir()
    page_path.write_text(
        'Before\n{% include-markdown "\\_snippets/wrapper.md" %}\nAfter\n',
        encoding="utf-8",
    )
    (snippets_dir / "wrapper.md").write_text(
        '{% include-markdown "_snippets/nested.md" %}\n',
        encoding="utf-8",
    )
    (snippets_dir / "nested.md").write_text("[Guide](../guide.md#intro)\n", encoding="utf-8")

    prepare_zensical_docs._expand_include_markdown_directives(  # pyright: ignore[reportPrivateUsage]
        docs_dir
    )

    assert page_path.read_text(encoding="utf-8") == "Before\n[Guide](../guide.md#intro)\nAfter\n"
    assert not snippets_dir.exists()


@pytest.mark.parametrize(
    ("directive", "message"),
    [
        ('{% include-markdown "_snippets/missing.md" %}', "does not exist"),
        ('{% include-markdown "../outside.md" %}', "escapes"),
        ('{% include-markdown "_snippets/item.md" start="1" %}', "Unsupported"),
    ],
)
def test_expand_include_markdown_directives_rejects_unsupported_or_missing_includes(
    tmp_path: Path,
    directive: str,
    message: str,
) -> None:
    """The adapter fails rather than silently accepting unsupported include syntax."""
    docs_dir: Path = tmp_path / "docs"
    docs_dir.mkdir()
    (docs_dir / "page.md").write_text(f"{directive}\n", encoding="utf-8")

    with pytest.raises((FileNotFoundError, ValueError), match=message):
        prepare_zensical_docs._expand_include_markdown_directives(  # pyright: ignore[reportPrivateUsage]
            docs_dir
        )


def test_expand_include_markdown_directives_rejects_cycles(
    tmp_path: Path,
) -> None:
    """Recursive snippet references report their inclusion cycle."""
    docs_dir: Path = tmp_path / "docs"
    snippets_dir: Path = docs_dir / "_snippets"
    docs_dir.mkdir()
    snippets_dir.mkdir()
    (docs_dir / "page.md").write_text(
        '{% include-markdown "_snippets/first.md" %}\n',
        encoding="utf-8",
    )
    (snippets_dir / "first.md").write_text(
        '{% include-markdown "_snippets/second.md" %}\n',
        encoding="utf-8",
    )
    (snippets_dir / "second.md").write_text(
        '{% include-markdown "_snippets/first.md" %}\n',
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match="Include cycle"):
        prepare_zensical_docs._expand_include_markdown_directives(  # pyright: ignore[reportPrivateUsage]
            docs_dir
        )
