# topmark:header:start
#
#   project      : TopMark
#   file         : ci.yml
#   file_relpath : .github/workflows/ci.yml
#   license      : MIT
#   copyright    : (c) 2025 Olivier Biot
#
# topmark:header:end

name: CI

on:
    pull_request:
        paths:
            - "src/**"
            - "tests/**"
            - "tools/**"
            - "docs/**"
            - "mkdocs.yml"
            - "constraints.txt"
            - "pyproject.toml"
    push:
        branches: [main]
        tags:
            - "v*"

jobs:
    # Detect what changed in the PR so we can cheaply gate jobs.
    changes:
        if: ${{ github.event_name == 'pull_request' }}
        runs-on: ubuntu-latest
        outputs:
            src_changed: ${{ steps.filter.outputs.src }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - id: filter
              uses: dorny/paths-filter@v3
              with:
                  filters: |
                      src:
                        - 'src/**'
                        - 'tests/**'
                        - 'tools/**'
            - run: echo "src_changed=${{ steps.filter.outputs.src }}"

    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - uses: actions/checkout@v4
            - id: setup-python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
                  cache: pip
                  cache-dependency-path: |
                      requirements-*.txt
                      constraints.txt
            - name: Cache pip & tox
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                      .tox
                  key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('tox.ini', 'pyproject.toml', 'requirements-*.txt', 'constraints.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-
            - name: Bootstrap tox
              run: |
                  python -m pip install -U pip
                  pip install tox
            - name: Lint & type-check via tox
              run: |
                  tox -e format-check
                  tox -e lint
                  tox -e docstring-links

    pre-commit:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v4
            - id: setup-python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
                  cache: pip
                  cache-dependency-path: |
                      requirements-*.txt
                      constraints.txt
            - name: Cache pip
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                  key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('pyproject.toml', '.pre-commit-config.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-
            - name: Install pre-commit
              run: |
                  python -m pip install -U pip
                  pip install pre-commit
            - name: Run pre-commit hooks
              env:
                  SKIP: lychee-md,lychee-src,pyright,docstring-ref-links
              run: pre-commit run --all-files --show-diff-on-failure

    docs:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - uses: actions/checkout@v4
            - id: setup-python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
                  cache: pip
                  cache-dependency-path: |
                      requirements-*.txt
                      constraints.txt
            - name: Cache pip & tox
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                      .tox
                  key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('tox.ini', 'pyproject.toml', 'requirements-*.txt', 'constraints.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-
            - name: Bootstrap tox
              run: |
                  python -m pip install -U pip
                  pip install tox
            - name: Build docs (strict via tox)
              run: tox -e docs

    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        steps:
            - uses: actions/checkout@v4
            - id: setup-python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  allow-prereleases: true
                  cache: pip
                  cache-dependency-path: |
                      requirements-*.txt
                      constraints.txt
            - name: Cache pip & tox
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                      .tox
                  key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('tox.ini', 'pyproject.toml', 'requirements-*.txt', 'constraints.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-
            - name: Bootstrap tox
              run: |
                  python -m pip install -U pip
                  pip install tox
            - name: Run tox tests for ${{ matrix.python-version }}
              run: |
                  case "${{ matrix.python-version }}" in
                    "3.10") tox -e py310 ;;
                    "3.11") tox -e py311 ;;
                    "3.12") tox -e py312 ;;
                    "3.13") tox -e py313 ;;
                    "3.14") tox -e py314 ;;
                  esac

    api-snapshot:
        name: API Snapshot
        # Fast, PR-only check that runs ONLY when src/** changed.
        needs: changes
        if: ${{ github.event_name == 'pull_request' && needs.changes.outputs.src_changed == 'true' }}
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v4
            - id: setup-python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
                  cache: pip
                  cache-dependency-path: |
                      requirements-*.txt
                      constraints.txt
            - name: Cache pip & tox
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                      .tox
                  key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('tox.ini', 'pyproject.toml', 'requirements-*.txt', 'constraints.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-
            - name: Bootstrap tox
              run: |
                  python -m pip install -U pip
                  pip install tox
            - name: Run API snapshot check (py313)
              run: tox -e py313-api

    links:
        # Use official lychee Action; no cargo needed
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check links in docs and top-level Markdown
              uses: lycheeverse/lychee-action@v1
              with:
                  args: >-
                      --config lychee.toml
                      --no-progress
                      --verbose
                      docs
                      *.md
