# topmark:header:start
#
#   project      : TopMark
#   file         : ci.yml
#   file_relpath : .github/workflows/ci.yml
#   license      : MIT
#   copyright    : (c) 2025 Olivier Biot
#
# topmark:header:end

name: CI

on:
  pull_request:
    paths:
      - "src/**"
      - "docs/**"
      - "mkdocs.yml"
      - "constraints.txt"
      - "pyproject.toml"
      - "tools/**"
  push:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }
      - name: Install (dev+docs)
        run: |
          python -m pip install -U pip
          pip install -c constraints.txt -e .[dev,docs]
      - name: Lint & types & headers
        run: |
          ruff format --check .
          ruff check .
          pyright
          topmark-check
      - name: Custom docstring checks
        run: python tools/check_docstrings.py --stats
      - name: Build docs (strict)
        run: mkdocs build --strict