# topmark:header:start
#
#   project      : TopMark
#   file         : release.yml
#   file_relpath : .github/workflows/release.yml
#   license      : MIT
#   copyright    : (c) 2025 Olivier Biot
#
# topmark:header:end

name: Release to PyPI

on:
  push:
    tags:
      - "v*.*.*"       # e.g., v1.2.3 (final)
      - "v*.*.*-rc*"   # e.g., v1.2.3-rc1 (pre-release to TestPyPI)

permissions:
  contents: read
  id-token: write   # REQUIRED for PyPI/TestPyPI Trusted Publishing (OIDC)

concurrency:
  group: pypi-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish-pypi:
    if: ${{ !contains(github.ref, '-rc') }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build sdist and wheel
        run: |
          python -m pip install -U pip build
          python -m build

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true

  publish-testpypi:
    if: ${{ contains(github.ref, '-rc') }}
    runs-on: ubuntu-latest
    environment:
      name: testpypi
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build sdist and wheel
        run: |
          python -m pip install -U pip build
          python -m build

      - name: Publish to TestPyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          attestations: true

  github-release:
    if: ${{ !contains(github.ref, '-rc') }}
    needs: publish-pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true